
POST http://127.0.0.1:8000/auth/register
Content-Type: application/json

{
    "first_name":"Brian",
    "last_name":"Aira",
    "email":"brianaira622@gmail.com",
    "phone":"2622698336",
    "address":"Calle falsa 123",
    "password":"123456"

}
###
POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
    "email":"brianaira622@gmail.com",   
    "password":"123456"
    
}
 ###{
# "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwiaWF0IjoxNzYwMDU2Nzk0LCJleHAiOjE3NjAwNTg1OTR9.hDHtQ4apAka9kgtPMfP3CAvK4KOA0k-_Md-I9e44qj4",
#   "token_type": "bearer"
### }